// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOD33B_FtVXdZCdPe5sKrVOybjYgjJOY',
    appId: '1:317167114617:web:24b44974e4e2e76a55f7a8',
    messagingSenderId: '317167114617',
    projectId: 'zivo-63f15',
    authDomain: 'zivo-63f15.firebaseapp.com',
    storageBucket: 'zivo-63f15.firebasestorage.app',
    measurementId: 'G-152GFG560Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFcBrJAreMEIH4ltObRNXs-h1ZlmMcU8',
    appId: '1:317167114617:android:e4fd2ec7f3ae385855f7a8',
    messagingSenderId: '317167114617',
    projectId: 'zivo-63f15',
    storageBucket: 'zivo-63f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBQV7awQtpsFR-0vVWccJufXOP1FhkvQ',
    appId: '1:317167114617:ios:fb766e1151cf147755f7a8',
    messagingSenderId: '317167114617',
    projectId: 'zivo-63f15',
    storageBucket: 'zivo-63f15.firebasestorage.app',
    iosClientId: '317167114617-0121shq836kobi92npegqpu6vv9m3p3q.apps.googleusercontent.com',
    iosBundleId: 'com.ziadelsewedy.zivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBQV7awQtpsFR-0vVWccJufXOP1FhkvQ',
    appId: '1:317167114617:ios:48a44af3d8eaa12455f7a8',
    messagingSenderId: '317167114617',
    projectId: 'zivo-63f15',
    storageBucket: 'zivo-63f15.firebasestorage.app',
    iosClientId: '317167114617-p9op0do1au4helde6rek6banju8dt29e.apps.googleusercontent.com',
    iosBundleId: 'com.example.zivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjOD33B_FtVXdZCdPe5sKrVOybjYgjJOY',
    appId: '1:317167114617:web:3efdca8d61eaaccb55f7a8',
    messagingSenderId: '317167114617',
    projectId: 'zivo-63f15',
    authDomain: 'zivo-63f15.firebaseapp.com',
    storageBucket: 'zivo-63f15.firebasestorage.app',
    measurementId: 'G-VD8MQHBG88',
  );
}
