// File generated by hand to match the FlutterFire CLI output shape.
//
// The FlutterFire CLI currently cannot discover the (verified) Firebase
// project on this machine, so these values were transcribed directly from the
// verified `ios/Runner/GoogleService-Info.plist` for the registered ZIVO iOS
// app — not invented. Regenerate with `flutterfire configure` once the CLI can
// see the project, and add other platforms as they are registered in Firebase.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform. '
          'Only the iOS app is currently registered in the ZIVO Firebase '
          'project; register the target in Firebase and rerun the FlutterFire '
          'CLI to add it here.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBQV7awQtpsFR-0vVWccJufXOP1FhkvQ',
    appId: '1:317167114617:ios:48a44af3d8eaa12455f7a8',
    messagingSenderId: '317167114617',
    projectId: 'zivo-63f15',
    storageBucket: 'zivo-63f15.firebasestorage.app',
    iosClientId:
        '317167114617-p9op0do1au4helde6rek6banju8dt29e.apps.googleusercontent.com',
    iosBundleId: 'com.example.zivo',
  );
}
